config/routes.rb
AndnowServer::Application.routes.draw do
  resources :sessions, :except => [:show]
  post 'sessions/import' => 'sessions#import'

  resource :user, :only => [:show, :update]

  resources :tokens, :only => [:destroy, :create]

  get 'home' => 'home#index'
  get 'home/login' => 'home#login', as: 'login'
  get 'home/logout' => 'home#logout', as: 'logout'
  post 'home/verify' => 'home#verify', as: 'verify'

  get 'activity/:activity' => 'activity#show', as: 'activity'

  root :to => 'home#index'
end

app/models/session.rb
class Session < ActiveRecord::Base
  validates :description, :presence => true
  validates :user_id, :presence => true
  belongs_to :user

  def delete_duplicates
    Session.where([
      'description = ? AND start_time = ? AND user_id = ?',
      description,
      start_time,
      user.id
    ]).delete_all
  end

  def self.create_for user, params
    session = Session.new params
    session.user = user
    session.delete_duplicates
    session.save
  end
end

app/models/token.rb
class Token < ActiveRecord::Base
  validates :key, :presence => true
  validates :key, :uniqueness => true
  validates :user_id, :presence => true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :presence => true
  validates :email, :uniqueness => true
  has_many :tokens
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  before_filter :require_login

  def show
    @sessions = Session.where(
      "user_id = ? AND description = ?",
      session[:user_id],
      params[:activity]
    ).order "start_time DESC"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
private
  def require_login
    unless logged_in?
      session[:url] = request.url
      redirect_to root_url
    end
    Time.zone = current_user.timezone if current_user and current_user.timezone
  end

  def logged_in?
    !!current_user
  end

  def current_user
    return nil unless session[:user_id] or params[:api_token]
    @current_user ||= User.find session[:user_id] if session[:user_id]
    token = Token.find_by_key params[:api_token] if params[:api_token]
    @current_user ||= token.user if token
    @current_user
  end
end

app/controllers/home_controller.rb
require 'net/http'

class HomeController < ApplicationController
  def index
    if logged_in?
      if session[:url]
        redirect_to session[:url]
        session[:url] = nil
      end
    else
      redirect_to :login
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to :login
  end

  def verify
    bid_resp = {}
    if params['assertion']
      http = Net::HTTP.new 'browserid.org', 443
      http.use_ssl = true
      response = http.post '/verify',
        "audience=#{request.host_with_port}&assertion=#{params['assertion']}",
        { 'Content-Type' => 'application/x-www-form-urlencoded' }
      begin
        bid_resp = JSON.parse response.body
        if bid_resp['status'] == 'okay'
          email = bid_resp['email']
          user = User.find_by_email email
          user = User.create email: email, token: Time.now.to_i unless user
          session[:user_id] = user.id
        end
      rescue JSON::ParserError
        logger.info 'BrowserId returning bad JSON?'
      end
    end
    render json: bid_resp
  end
end

app/controllers/sessions_controller.rb
require 'csv'

class SessionsController < ApplicationController
  before_filter :require_login

  def index
    @sessions = Session.where("user_id = ?", session[:user_id]).order "start_time DESC"

    respond_to do |format|
      format.html
      format.csv
      format.json { render json: @sessions }
    end
  end

  def show
    @session = Session.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @session }
    end
  end

  def new
    @session = Session.new
    @session.start_time = Time.now.to_i

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @session }
    end
  end

  def edit
    @session = Session.find(params[:id])
  end

  def import
    lines = params[:import][:csv].tempfile.readlines
    headers = CSV.parse(lines.shift).first
    while line = lines.shift
      Session.create_for current_user, CSV.parse(line, headers: headers).first.to_hash
    end
    redirect_to sessions_path
  end

  def create
    with_session do
      Session.where([
        'description = ? AND start_time = ? AND user_id = ?',
        @session.description,
        @session.start_time,
        @session.user.id
      ]).delete_all

      respond_to do |format|
        if @session.save
          format.html { redirect_to sessions_path, notice: 'Session was successfully created.' }
          format.json { render json: @session, status: :created, location: @session }
        else
          format.html { render action: "new" }
          format.json { render json: @session.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def update
    @session = Session.find(params[:id])

    respond_to do |format|
      if @session.update_attributes(params[:session])
        format.html { redirect_to sessions_path, notice: 'Session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @session = Session.find(params[:id])
    @session.destroy

    respond_to do |format|
      format.html { redirect_to sessions_url }
      format.json { head :no_content }
    end
  end
private
  def with_session
    session_params = params[:session]
    return unless session_params
    session_params.delete :user_id
    session_params[:description].strip! if session_params[:description]
    @session = Session.new session_params
    @session.user = current_user
    yield
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_filter :require_login

  def create
    token = Token.new params[:token]
    token.user = current_user
    token.save
    redirect_to user_url
  end

  def destroy
    Token.find(params[:id]).destroy
    redirect_to user_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login

  def show
    @user = current_user
    @token = Token.new key: params[:key], user: @user
  end

  def update
    current_user.update_attributes params[:user]
    redirect_to user_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
require 'digest/md5'

module ProfileHelper
  def gravatar_url email
    hash = Digest::MD5.hexdigest email.downcase
    "http://www.gravatar.com/avatar/#{hash}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def time s
    return '' unless s
    Time.zone.at(s).strftime '%a %d %b %H:%M:%S'
  end

  def duration from, to
    return '' unless from and to
    s = to - from
    minutes,s=s/60,s%60
    hours,minutes=minutes/60,minutes%60
    return "#{hours} hours #{minutes} minutes" if hours > 0
    return "#{minutes} minutes #{s} seconds" if minutes > 0
    "#{s} seconds"
  end

  def cost c
    return '' unless c
    d,c=c/100,c%100
    "$#{d}.#{c}"
  end
end

app/views/activity/show.html.slim
table.table.table-striped
  thead
    tr
      th Start
      th End
      th Duration
      th Count
      th Cost
      th Notes
      th
      th
      th

  - @sessions.each do |session|
    tr
      td = time session.start_time
      td = time session.end_time
      td = duration session.start_time, session.end_time
      td = session.count
      td = cost session.cost
      td = session.notes
      td
        = link_to edit_session_path(session), class: 'e' do
          i.icon-edit
      td
        = link_to session, class: 'd', confirm: 'Are you sure?', method: :delete do
          i.icon-remove-circle

app/views/home/index.html.erb
<% content_for :navbar_left do %>
  <li class="active"><%= link_to 'Home', root_url %></li>
  <li><%= link_to 'Sessions', sessions_url %></li>
  <li><%= link_to 'Profile', user_url %></li>
<% end %>

<% content_for :js do %>
  <%= javascript_include_tag 'keyboard' %>
<% end %>

<div class="hero-unit">
  <h1>ok now what?</h1>
  <p class="lead">whereupon you are convinced to gather seemingly irrelevant data about yourself</p>
</div>

<div class="row">
  <div class="span4">
    <h2>Day</h2>
  </div>
  <div class="span4">
    <h2>Week</h2>
  </div>
  <div class="span4">
    <h2>Month</h2>
  </div>
</div>

app/views/home/login.html.erb
<% content_for :navbar_right do %>
  <li><a id="authenticate"><i class="icon-lock icon-white"></i> login</a></li>
<% end %>

<% content_for :js do %>
  <script src="https://browserid.org/include.js" type="text/javascript"></script>
  <%= javascript_include_tag 'login' %>
<% end %>

<div class="hero-unit">
  <h1>Quantify your life</h1>
  <p class="lead">an experimental project to facilitate obsessively capturing information about your life</p>
</div>

<div class="row">
  <div class="span12">
    <h2>The Pitch</h2>
    <p>The initial idea of this project was just to provide a simple mechanism to capture a timestamp as activities are started and again when they are finished</p>
    <p>You can also now capture counts with each session of a specific activity and
    a cost</p>
    <p>Various graphs and charts will appear over time to try to assist in interpreting and analysing this informtation</p>
  </div>
</div>

<div class="row">
  <div class="span3 well">
    <h3>Step 1</h3>
    <p>Create a <a href="https://browserid.org">browserid</a> account associated with your email address and log in</p>
  </div>
  <div class="span3 well">
    <h3>Step 2</h3>
    <p>Install the <a href="/AndnowDroid.apk">android client</a> application and configure your API token</p>
  </div>
  <div class="span3 well">
    <h3>Step 3</h3>
    <p>Start timing/counting anything you think might reveal interesting information</p>
  </div>
</div>

<hr>

<div class="row">
  <div class="span12">
    <h2>The Source</h2>
  </div>
</div>

<div class="row">
  <div class="span5 well">
    <h2>Web Application</h2>
    <p>The web backend is a rails 3.2.1 application.  The source can be found <a href="https://github.com/markryall/andnow_rails">here</a></p>
  </div>
  <div class="span5 well">
    <h2>Android Client</h2>
    <p>The android client application has been built and tested on 2.3.6 (a Samsung Galaxy SII).  The source can be found <a href="https://github.com/markryall/andnow_rails">here</a></p>
  </div>
</div>

<hr>

<div class="row">
  <div class="span2">
    <h2>Host your own</h2>
    <p>You may prefer to deploy your own instance of this application</p>
    <p>It's really simple to get an instance up and running in heroku in a few short steps</p>
  </div>
  <div class="span5">
    <pre class="linenums">
    git clone git://github.com/markryall/andnow_rails.git
    cd andnow_rails
    bundle
    heroku apps:create -s cedar
    git push heroku master
    heroku run rake db:migrate
    heroku config:add SECRET=`rake secret`
    heroku ps:restart
    </pre>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">and now?</a>
          <div class="nav-collapse">
            <ul class="nav">
              <%= yield :navbar_left %>
            </ul>
          </div>
          <ul class="nav pull-right">
            <% if content_for? :navbar_right %>
              <%= yield :navbar_right %>
            <% else %>
              <li><a href="/home/logout"><i class="icon-lock icon-white"></i> logout <%= @current_user.email %></a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <% if notice %>
        <div class="alert alert-success">
          <%= notice %>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
    <%= yield :js %>
  </body>
</html>

app/views/layouts/sessions.html.erb
<% content_for :navbar_left do %>
  <li><%= link_to 'Home', root_url %></li>
  <li class="active"><%= link_to 'Sessions', sessions_url %></li>
  <li><%= link_to 'Profile', user_url %></li>
<% end %>

<% content_for :js do %>
  <%= javascript_include_tag 'keyboard' %>
<% end %>

<%= render :template => 'layouts/application' %>

app/views/layouts/users.html.erb
<% content_for :navbar_left do %>
  <li><%= link_to 'Home', root_url %></li>
  <li><%= link_to 'Sessions', sessions_url %></li>
  <li class="active"><%= link_to 'Profile', user_url %></li>
<% end %>

<% content_for :js do %>
  <%= javascript_include_tag 'keyboard' %>
<% end %>

<%= render :template => 'layouts/application' %>

app/views/users/show.html.slim
div.hero-unit
  div.span1.offset3
    img src={gravatar_url @user.email}
  div.span4
    h1 = @user.email

div.row
  div.span6
    h2 Timezone
    = form_for @user, html: {class: 'form-horizontal'} do |f|
      = f.time_zone_select :timezone
      = f.submit 'Update', class: 'btn btn-primary'

  div.span6
    h2 Tokens
    ul
      - @user.tokens.each do |token|
        li
          = token.key
          = link_to token, confirm: 'Are you sure?', method: :delete do
            i.icon-remove-circle

    = form_for @token, html: {class: 'form-horizontal'} do |f|
      = f.text_field :key, placeholder: 'API Token', class: 'input-xlarge'
      = f.submit 'Create', class: 'btn btn-primary'